#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}"
DIR_PATH=$(dirname "$SCRIPT_PATH")
echo "-------------------------------------------------------------"
echo "----------------------cocker-compose-------------------------"
echo "-------------------------------------------------------------"
cat $DIR_PATH/cocker.txt
echo "\\n\\n\\n"                                                                
echo "-------------------------------------------------------------"
echo "Hace lo mismo que docker-compose, pero te muestra un perrito"
echo "-------------------------------------------------------------"
sleep 2
docker-compose "$@"

