#!/bin/bash

if [ -x "$(command -v docker-compose)" ]; then
    COMMAND="docker-compose"
elif $(docker compose &>/dev/null) && [ $? -eq 0 ]; then
    COMMAND="docker compose"
else
    echo "Sin docker compose no hay cocker compose. Lo siento. No negociamos."
    exit 1
fi

SCRIPT_PATH="${BASH_SOURCE[0]}"
DIR_PATH=$(dirname "$SCRIPT_PATH")
echo "-------------------------------------------------------------"
echo "----------------------cocker-compose-------------------------"
echo "-------------------------------------------------------------"
cat $DIR_PATH/cocker.txt
echo "\\n\\n\\n"                                                                
echo "-------------------------------------------------------------------"
echo "Hace lo mismo que $COMMAND, pero te muestra un perrito cocker"
echo "-------------------------------------------------------------------"
sleep 1
$COMMAND "$@"

